on: deployment

jobs:
    build:
        runs-on: registry.please-open.it/mdpdf:master
        steps:
            - name: Markdown-to-pdf Generator
            - run: git log --date=short --pretty=format:' | %ad | %ae | %s | '  HEAD >> CHANGELOG.md
